Update KSU_Next_6.6.89_.yml

diff --git a/.github/workflows/KSU_Next_6.6.89_.yml b/.github/workflows/KSU_Next_6.6.89_.yml
--- a/.github/workflows/KSU_Next_6.6.89_.yml
+++ b/.github/workflows/KSU_Next_6.6.89_.yml
@@ -1,4 +1,4 @@
-name: KernelSU Next OP13 Build 6.6.89 cct18 
+name: KernelSU Next OP13 Build 6.6.89
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}-6.6.89
@@ -452,15 +452,15 @@ jobs:
       - name: Apply LZ4 1.10.0 & ZSTD 1.5.7 Patches
         if: inputs.lz4_enable
         run: |
-          echo "正在添加lz4 1.10.0 & zstd 1.5.7补丁…"
-          cd kernel_workspace
-          git clone --depth=1 https://github.com/$GITHUB_REPOSITORY.git -b $GITHUB_REF_NAME $GITHUB_ACTOR
-          cp ./$GITHUB_ACTOR/zram_patch/001-lz4.patch ./common/
-          cp ./$GITHUB_ACTOR/zram_patch/lz4armv8.S ./common/lib
-          cp ./$GITHUB_ACTOR/zram_patch/002-zstd.patch ./common/
-          cd ./common
-          git apply -p1 < 001-lz4.patch || true
-          patch -p1 < 002-zstd.patch || true
+          echo "Adding LZ4 & ZSTD patches..."
+          cd kernel_workspace/common
+          mkdir -p lib/lz4/lz4armv8
+          cp ../kernel_patches/zram/001-lz4.patch ./
+          cp ../kernel_patches/zram/lz4armv8.S lib/lz4/lz4armv8.S
+          cp ../kernel_patches/zram/lz4armv8.S lib/lz4/lz4armv8/lz4armv8.S
+          cp ../kernel_patches/zram/002-zstd.patch ./
+          git apply -p1 < 001-lz4.patch || echo "LZ4 Patch failed or already applied"
+          patch -p1 < 002-zstd.patch || echo "ZSTD Patch failed or already applied"
 
       - name: Apply LZ4KD Patch
         if: inputs.lz4kd_enable
